### ISSUE TITLE
Feature Request: Add mil/thou (thousandth of an inch)

### ISSUE THREAD

**Issue by scandey** [alfredapp/unit-converter-workflow#3]
### Feature details

I work in circuit design and the dominant unit (unfortunately) remains the mil (or thou), [a thousandth of an inch](https://en.wikipedia.org/wiki/Thousandth_of_an_inch). I regularly convert mils to mm when switching back and forth between systems of units and it would be great to do in Alfred. I do realize the mil is confusing, as it is more logically an abbreviation for millimeter, so perhaps thou would be an acceptable addition?

**Comment by vitorgalvao** [comment]
Can you give [this version](https://github.com/alfredapp/unit-converter-workflow/files/14872605/Unit.Converter.alfredworkflow.zip) a spin and see if it works as expected? I used `thou` for the symbol.

**Comment by scandey** [comment]
Works wonderfully, thank you!
