### ISSUE TITLE
Support Currencies?

### ISSUE THREAD

**Issue by kalaschnik** [alfredapp/unit-converter-workflow#4]
### Feature details

I am using @deanishe’s [alfred-convert](https://github.com/deanishe/alfred-convert), which has a convenient currencies converter included. Are there any plans to include one?

**Comment by vitorgalvao** [comment]
That workflow is no longer under development, @giovannicoppola [has a fork](https://alfred.app/workflows/giovanni/convert/).

As for the question, Currency Conversion [is in another workflow](https://alfred.app/workflows/alfredapp/currency-converter/). As [explained on the forum](https://www.alfredforum.com/topic/21297-unit-converter-—-convert-between-different-units-of-measurement/#comment-113771):

> Currency conversion was planned as a different workflow from the start, because it’s a different type of measurement that changes unpredictably over time and requires an internet connection, the APIs are completely separate. This allows having each workflow play to their strengths

**Comment by kalaschnik** [comment]
Great resources. Thanks!
